Repository infrae/Products.Formulator, pull requests merged in 2022-10, with the labels that each got.

#5 Fix test setup so it can run on Zope 2.13.30.
  .github/workflows/tests.yml
  MANIFEST.in
  buildout-base.cfg
  buildout.cfg
  buildout213.cfg
  buildout4.cfg
Labels: bug, enhancement, hacktoberfest-accepted

#4 Fix isort.
  .github/workflows/tests.yml
  .meta.toml
  setup.cfg
  src/Products/Formulator/Form.py
  src/Products/Formulator/Validator.py
  tox.ini
Labels: enhancement, hacktoberfest-accepted

#6 Zope4 compatibility
  CHANGES.rst
  MANIFEST.in
  README.rst
  buildout213.cfg
  setup.py
  src/Products/Formulator/FSForm.py
  src/Products/Formulator/Field.py
  src/Products/Formulator/FieldHelpTopic.py
  src/Products/Formulator/FieldRegistry.py
  src/Products/Formulator/Form.py
  src/Products/Formulator/ProductForm.py
  src/Products/Formulator/__init__.py
  src/Products/Formulator/configure.zcml
  src/Products/Formulator/dtml/FieldHelpTopic.dtml
  src/Products/Formulator/ftesting.zcml
  src/Products/Formulator/help/dogfood.txt
  src/Products/Formulator/testing.py
  src/Products/Formulator/tests/test_serialize.py
  src/Products/Formulator/tests/test_validators.py
  src/Products/Formulator/zeamsupport.py
  tox.ini
Labels: hacktoberfest-accepted
